version: '3'
services:
   redis:
    image: redis:5.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
     - "6379:6379"
    networks:
      default:
        aliases:
          - svc.redis.io
    volumes:
      - redis-data:/data

networks:
  default:
    external:
      name: net

volumes:
  redis-data:
